version: '3.5'

services:
  cadvisor:
    image: google/cadvisor:latest
    deploy:
      mode: global
    volumes:
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - 9089:8080      
  node-exporter:
    image: prom/node-exporter    
    deploy:
      mode: global    
    volumes:
      - /proc:/host/proc
      - /sys:/host/sys
      - /:/rootfs
      - /etc/hostname:/etc/host_hostname    
    ports:
      - 9100:9100            
  prometheus:
    image: prom/prometheus
    volumes:      
      - 'prometheus:/etc/prometheus'
    ports:
      - 9090:9090  
  grafana:
    image: grafana/grafana
    volumes:            
      - 'grafana_provisioning:/etc/grafana/provisioning'    
      - 'grafana_storage:/var/lib/grafana'
    ports:
      - 3000:3000     
volumes:   
  prometheus:
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_ADDR},nolock,soft,rw"
      device: ":${NFS_SHARE}${PROMETHEUS_VOLUME_PATH}"               
  grafana_provisioning:
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_ADDR},nolock,soft,rw"
      device: ":${NFS_SHARE}${GRAFANA_VOLUME_PROVISIONING_PATH}"   
  grafana_storage:
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_ADDR},nolock,soft,rw"
      device: ":${NFS_SHARE}${GRAFANA_VOLUME_STORAGE_PATH}"               
networks:
  default:
    external: 
      name: multi-host